create_orders_table = """
CREATE TABLE IF NOT EXISTS ORDERS (
ID VARCHAR(255) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(255) NOT NULL,
TIMESTAMP VARCHAR(255) NOT NULL,
STATUS VARCHAR(255) NOT NULL);
""" 

create_drinks_table = """
CREATE TABLE IF NOT EXISTS DRINKS (
ID VARCHAR(255) PRIMARY KEY NOT NULL,
NAME VARCHAR(255) NOT NULL,
PRICE FLOAT NOT NULL);
INSERT OR IGNORE INTO DRINKS (ID, NAME, PRICE) VALUES
('small_beer', 'Small Beer', 2.7),
('large_beer', 'Large Beer', 3.2),
('whiskey', 'Whiskey', 3.0),
('wine', 'Wine', 4.0),
('vodka', 'Vodka', 2.5),
('borovicka', 'Borovicka', 2.0);
"""

create_orderItems_table = """
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
ID INT PRIMARY KEY,
ORDER_ID VARCHAR(255) NOT NULL REFERENCES ORDERS(ID) ON DELETE CASCADE,
DRINK_ID VARCHAR(255) NOT NULL REFERENCES DRINKS(ID),
QTY INT NOT NULL,
PRICE FLOAT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_order_drink
  ON order_items(order_id, drink_id);
"""